namespace:
  create: true # helm -n devops-tools --create-namespace (recomendado)
  name: devops-tools

image:
  repository: jenkins/jenkins
  tag: "lts@sha256:4b4a5eb0f69af5e48c9f55c0aa58da5d098eae1a4156d1e540f2f35c933b8695"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: jenkins-admin # si vacío, usa fullname
  annotations: {}

rbac:
  create: true # si tu cluster NO tiene RBAC, déjalo en false

service:
  type: LoadBalancer # LoadBalancer | ClusterIP | NodePort
  port: 8080
  targetPort: 8080
  nodePort: null # solo si type=NodePort
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /
    prometheus.io/port: "8080"
  exposeAgentPort: false # expone el 50000 en el Service

ingress:
  enabled: false
  className: nginx
  tls:
    - secretName: jenkins-tls
      hosts: [jenkins.example.com]
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "120"
  hosts:
    - host: jenkins.example.com
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: "500m"
    memory: "500Mi"
  limits:
    cpu: "1"
    memory: "2Gi"

persistence:
  enabled: true
  accessModes: ["ReadWriteOnce"]
  size: 20Gi
  storageClassName: managed-csi # AKS CSI disk
  existingClaim: "" # si ya tienes un PVC creado, pon el nombre aquí y no se creará otro

securityContext:
  runAsUser: 1000
  fsGroup: 1000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: RuntimeDefault

nodeSelector: {}
tolerations: []
affinity: {}

probes:
  liveness:
    path: /login
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
  readiness:
    path: /login
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1 # ver nota de RWX/HA
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

podSecurityContext:
  runAsUser: 1000
  runAsNonRoot: true
  fsGroup: 1000

extraEnv:
  - name: JENKINS_OPTS
    value: "--argumentsRealm.roles.user=user --argumentsRealm.roles.admin=admin --sessionTimeout=30"

extraVolumes:
  - name: kv
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: kv-jenkins
extraVolumeMounts:
  - name: kv
    mountPath: /mnt/kv
    readOnly: true

azure:
  tenantId: "<tu-tenant>"
keyVault:
  name: "<tu-kv>"
