{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "jenkins.fullname" . }}-admin
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
{{- end }}