apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: { { .Release.Namespace } }
spec:
  limits:
    - type: Container
      default:
        cpu: "1"
        memory: "2Gi"
      defaultRequest:
        cpu: "500m"
        memory: "512Mi"
