apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "jenkins.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "jenkins.name" . }}
  policyTypes: ["Ingress","Egress"]
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
    ports:
    - port: 8080
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system # DNS
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0 # <-- reemplaza por rangos de tu Git/SCM, proxy corporativo, repos plugin, etc.
    ports:
    - port: 443
      protocol: TCP