apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
    name: { ? { include "jenkins.fullname" . } }
    namespace: { ? { .Release.Namespace } }
spec:
    minAvailable: 1
    selector:
        matchLabels:
            app: jenkins-server