{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "jenkins.fullname" . }}-pdb
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "jenkins.selectorLabels" . | nindent 8 }}
  {{- with .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  {{- with .Values.pdb.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
{{- end }}