{{- if and .Values.secretProviderClass.enabled .Values.keyVault.name .Values.azure.tenantId }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-jenkins
  # TIP: puedes omitir namespace y dejar que Helm use .Release.Namespace
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"
    keyvaultName: {{ .Values.keyVault.name | quote }}
    tenantId: {{ .Values.azure.tenantId | quote }}
    objects: |
      array:
        - objectName: jenkins-admin-password
          objectType: secret
  secretObjects:
    - secretName: jenkins-admin
      type: Opaque
      data:
        - objectName: jenkins-admin-password
          key: password
{{- end }}