{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "jenkins.fullname" .) .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}